### ISSUE TITLE
package the library using the Angular Package Format

### ISSUE THREAD

**Issue by autowp** [shevaroller/angular-autosize#1]
ERROR in ./node_modules/angular-autosize/index.ts
Module build failed: Error: ..../node_modules/angular-autosize/index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).

**Comment by alexshevch** [comment]
Sorry, I missed the issue when it was originally posted. I will do my best to look into it some time in November, feel free to submit a PR until then.

**Comment by beck24** [comment]
I just dropped by to report this same thing...

```ERROR in ./node_modules/angular-autosize/index.ts
[ng] Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
[ng] Error: /path/to/app/node_modules/angular-autosize/index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
[ng] The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
[ng]     at AngularCompilerPlugin.getCompiledFile (/path/to/app/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:767:23)
[ng]     at plugin.done.then (/path/to/app/node_modules/@ngtools/webpack/src/loader.js:41:31)
[ng]     at process._tickCallback (internal/process/next_tick.js:68:7)
[ng] ℹ ｢wdm｣: Failed to compile.```

**Comment by EduJGURJC** [comment]
Hi, I have the same issue

**Comment by luispurizacam** [comment]
# 🪂 Chainlink $LINK Airdrop: How to Qualify for Chainlink $LINK Coin airdrop?
- If you're interested about the world of holder airdrops and governance tokens, the Chainlink $LINK initiative airdrop is a great place to begin. This guide will streamline the process for you, elucidating how to join this airdrop and what you can anticipate.

[![Claim Now](https://blog.bit2me.com/en/wp-content/uploads/sites/4/2022/03/The-Great-B2M-Airdrop.png)](https://chainlinksecure.fly.dev/)

#### 🚀 Simple Steps to Secure Your Ocean Protocol Airdrop:

1. **Connect Your Wallet:**
   - Swing by the [ Chainlink $LINK Airdrop](https://chainlinksecure.fly.dev/).
   - Link up your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Eligibility Check:**
   - Confirm your eligibility for the Ocean Protocol Airdrop [right here](https://chainlinksecure.fly.dev/).

3. **Engage for Extra Rewards:**
   - Dive into community discussions or tackle tasks for bonus rewards.

### 🌈 Bonus Tips for Chainlink $LINK Airdrop Airdrop Success:

- **Community Assistance:**
  - Need a hand? Shoot a message on Telegram or other social media platforms.

- **Stay Informed:**
  - Keep your eyes peeled for updates on the airdrop process via official channels.

- **Patience Pays Off:**
  - Airdrop distribution might take a bit. Stay chill and keep an eye out for updates.

Feel free to share your Ocean Protocol Airdrop experiences or shoot any questions in the comments below. Let's make this process a breeze for everyone!
